### ISSUE TITLE
No contribution guide

### ISSUE THREAD

**Issue by boxhock** [JohannEid/awesome-chainlink#1]
Hey, good job on the list!

I'd like to contribute, but noticed the contribution guide is missing 
>Any contribution to this repo is more then welcome follow this guide

Just thought I'd give you a heads up, and I'll submit contributions when there's a guide to it.

**Comment by JohannEid** [comment]
Hey, thank you appreciated ! 

I just added the contribution guide, it's just a step by step description on how to make a PR on Github. 

Looking forward to your contributions :)
